apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: coderancho/key_value_storage-fastapi:v0.1  # Updatse with your Docker Hub details
        ports:
        - containerPort: 80
